### ISSUE TITLE
Strange recursion in SASS

### ISSUE THREAD

**Issue by dillinger** [zurb/foundation-libsass-template#12]
After foundation update from 5.4.3 to 5.4.5, my compiled css(http://pastebin.com/YVbJfrEw) file becomes too heavy ~456kb. There only foundation css and there some strange recursion. Please need some advice. Thanks.

**Comment by gakimball** [comment]
Sorry that nobody got back to you, but this issue has been resolved.

Versions of Foundation prior to 5.5 are compatible with Ruby Sass 3.2 and 3.3, and libsass < 3.0. Foundation 5.5 is compatible with Ruby Sass 3.4 *only*, and libsass 3.0+.
