### ISSUE TITLE
node-sass package is incompatible with latest version of node

### ISSUE THREAD

**Issue by olefredrik** [zurb/foundation-libsass-template#16]
When using the latest stable version of node (v0.12.0), the ```npm install && bower install``` will fail. I get the following error message

```
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
```

A temporary solution (that works) is to switch back to node version 0.10.33.

I'm using the libsass version of Foundation in my FoundationPress repository. More info in this thread https://github.com/olefredrik/FoundationPress/issues/209. I'm looking for a better and more elegant solution. If you should get this to work with node v.0.12.0, feel free to share your insights :)

**Comment by GriffRocks** [comment]
Thank you @olefredrik this works perfectly with Foundation libsass.

**Comment by quakenul** [comment]
Just wanted to chime in. Took me a few frustrating hours of trial and error before I stumbled upon your post and was able to fix it. Thanks!

**Comment by victorleungtw** [comment]
Thanks @olefredrik! I got the same issue as well. Just a quick note on switching back to version 0.10:
1. Install nvm: curl https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | bash
2. nvm install 0.10
3. nvm use 0.10
fyi - https://github.com/creationix/nvm

**Comment by randmanrjr** [comment]
I think the issue is with the version of node-sass; the current package.json requires node-sass@1.2.3 but that is not compatible with node v.0.12.0.

I think node-sass@2.0.1 should be used for node v.0.12.0 compatibility.

I was able to get grunt to build by, updating the package.json to require node-sass@2.0.1 and then running npm update

But then grunt-sass install fails

then I ran npm install grunt-sass

and everything worked. grunt would build w/o errors

however, each time you run npm update, it will remove grunt-sass and you have to rerun npm install grunt-sass

I think this has something to do with npm cacheing, but I'm not sure.

not elegant, but will work with node v.0.12.0

I ended up switching to node v.0.10.23 via homebrew and everything works w/o any problems.

**Comment by randmanrjr** [comment]
I put in a pull request on the foundation-libsass-template repository to update the package.json to require node-sass v.2.0.1 and grunt-sass v.0.18.0.
If you edit your package.json and change these two dependecies, then run npm update, foundation cli with the -libsass flag will work with node v.0.12.0. It's also backwords compatible with node v0.10.33.

**Comment by dregini** [comment]
hi,
im newbie in web development, and i never used before node or scss, i tried to get foundation-press up and running without success... i keep getting the same error:
(i suppose is npm install)
--------------------------------
npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /var/www/html/wordpress/wp-content/themes/foundationpress
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
--------------------------------

I'm using centos as SO, initially I installed node 0.10.36 (with yum) and overwritten with the 0.10.33 that i've obtained with n.

Do you have any suggestion? or idea in what I'm doing wrong??

Sorry for my english (it's not my language)

**Comment by randmanrjr** [comment]
Hi,

try editing the package.json file and changing the following dependencies to the versions listed below:

“node-sass” : “~2.0.1”
“grunt-sass” : “~0.18.0”

then run npm update.

That is was worked for me.

Good luck.

**Comment by dregini** [comment]
worked!!! thank you!! 
you save my day :D

now i just have to understand why wordpress do not load the theme in the appearance manager...

**Comment by randmanrjr** [comment]
Make sure that you’ve uploaded the theme files to the correct directory in your wordpress install:

./wp-content/themes/FoundationPress

You may need to create the FoundationPress folder and then upload the theme via FTP.

**Comment by dregini** [comment]
solved the folder owner was me and not apache, changed that and everything was fine

Thanks again!

**Comment by nsberrow** [comment]
My issue was that the scss syntax had an error, exclude your scss files and then re-include them one by one.

**Comment by rtm3001** [comment]
In response to this thread, I changed version to 0.10. But still getting the error. Could you let me know what I can do to remedy this?

Ryans-MacBook-Pro-2:~ rmc8001$ source ~/.bashrc
Ryans-MacBook-Pro-2:~ rmc8001$ nvm use 0.10
Now using node v0.10.40 (npm v1.4.28)
Ryans-MacBook-Pro-2:~ rmc8001$ npm start
npm ERR! Error: ENOENT, open '/Users/rmc8001/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Darwin 14.3.0
npm ERR! command "/Users/rmc8001/.nvm/v0.10.40/bin/node" "/Users/rmc8001/.nvm/v0.10.40/bin/npm" "start"
npm ERR! cwd /Users/rmc8001
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /Users/rmc8001/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/rmc8001/npm-debug.log
npm ERR! not ok code 0
