### ISSUE TITLE
No _settings.scss?

### ISSUE THREAD

**Issue by illepic** [zurb/foundation-libsass-template#6]
Why is there no _settings.scss file included? I see it removed specifically in a prior commit. Also, the compass counterpart to this project includes a _settings.scss file.

**Comment by timaschew** [comment]
I don't know what this _settings file should do?
I don't use grunt, just node-sass and it doesn't work, the _settings file is never not included in any file?
And it doesn't matter if I change the original file installed by bower, or create my own

**Comment by gakimball** [comment]
This template is meant to be used with our CLI, which automatically copies the latest settings file from the Bower package into the `scss` folder. This prevents us from needing to update the settings file in multiple places every time we deploy a new version.

We should probably add a placeholder file that explains this, kind of like what [the Compass template](https://github.com/zurb/foundation-compass-template/blob/master/scss/_settings.scss) does.
